### ISSUE TITLE
Control buttons do not appear. Ubuntu 20.04

### ISSUE THREAD

**Issue by Alter-RK** [poehlerj/no-title-bar#11]
When the window is expanded, the buttons do not appear in the specified area. Check, please.
Here is a screen of the original extension on ubuntu 18.04 https://i.imgur.com/jHiLke6.png
This is on your Ubuntu 20.04 https://i.imgur.com/E7i8kYT.png

**Comment by poehlerj** [comment]
Will look into this later today, after updating to Gnome 3.36.

**Comment by poehlerj** [comment]
I was able to reproduce the problem and I think I fixed it - to be honest, I rewrote parts of the extension today, and now it just seems to work as intended. You can either wait for the extension to be officially reviewed and released, or check it out yourself for testing. Either way I will keep this issue open, until I have your feedback this is fixed.

**Comment by Alter-RK** [comment]
Thank you so much! a great extension and this is what you need !!!

**Comment by Alter-RK** [comment]
Note. There is another interesting extension. https://extensions.gnome.org/extension/1287/unite/

**Comment by poehlerj** [comment]
> Note. There is another interesting extension. https://extensions.gnome.org/extension/1287/unite/

I do know of unite. It inspired me to try and fix this extension, since they both hide the titlebar, but otherwise have completely different goals.
