### ISSUE TITLE
Repository description links to original extension on gnome.org

### ISSUE THREAD

**Issue by jmico** [poehlerj/no-title-bar#12]
Repository description "Integrates maximized windows with the top panel https://extensions.gnome.org"... links to original extension on gnome.org (https://extensions.gnome.org/extension/1267/no-title-bar/).

It should link to https://extensions.gnome.org/extension/2015/no-title-bar-forked/

Thanks for fixes :)

**Comment by poehlerj** [comment]
Wow, I did never notice that. Thank you for pointing this out to me! :+1:
