### ISSUE TITLE
External monitor support.

### ISSUE THREAD

**Issue by Archehandoro** [poehlerj/no-title-bar#14]
Device: Laptop
OS: Fedora 32
X: x11
Gnome: 3.36.2
WM: PapwerWM - https://github.com/paperwm/PaperWM

Titlte bars are removed from all apps as long as they are placed in the primary screen.

Laptop lid open: Title bars removed from laptop screen but no external monitor.
Laptop lid closed: Title bars removed from external monitor (now primary)

Thanks!

**Comment by poehlerj** [comment]
Is it possible, that you have the option "Hide titlebars only on primary monitor" active? Have a look at the settings page with tweak tools, or with gnome.extension.org

**Comment by Archehandoro** [comment]
> Is it possible, that you have the option "Hide titlebars only on primary monitor" active? Have a look at the settings page with tweak tools, or with gnome.extension.org

For the love of me I would have sworn that the option was disabled when I checked yesterday. But you are right, it was now enabled.

Thanks and apologies for not double checking.
