### ISSUE TITLE
Extension in Error state: No JS module 'tweener'

### ISSUE THREAD

**Issue by ironchicken** [poehlerj/no-title-bar#24]
I've installed from source following the instructions in the README. I'm using GNOME 3.38.0 (using X11 on Debian unstable).

In the Extension manager tool it shows the error:

    No JS module 'tweener' found in search path

**Comment by stefaca** [comment]
Identical problem, Shell 3.38.0 on Debian 10 Testing (Bullseye)

**Comment by moshiur-raj** [comment]
Same problem. Using gnome 3.38.1 on arch linux.

**Comment by rcdeoliveira** [comment]
Tweener was removed from gnome-shell in [PR 1200](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200), it seems removing any Tweener reference fix the issue.

[diff.txt](https://github.com/poehlerj/no-title-bar/files/5359440/diff.txt)

**Comment by juarezr** [comment]
Upgrading from Ubuntu 20.04 to 20.10 (Gnome 3.38) also broke this extension.

**Comment by DrShadow34** [comment]
No fix in main branch still? Tryed to install forked one with fix - no luck, same problem.

**Comment by Turgon-Aran-Gondolin** [comment]
Edit `no-title-bar@jonaspoehler.de/app_menu.js` and `buttons.js` file and change `imports.ui.tweener` to `imports.tweener.tweener` works for me.

**Comment by poehlerj** [comment]
This should be fixed by #25. Will upload to extensions.gnome.org later today. After Review this change should be available by the start of next week. Sorry, this took so long
