### ISSUE TITLE
New windows doesn't hide title bar

### ISSUE THREAD

**Issue by rcdeoliveira** [poehlerj/no-title-bar#3]
Sometimes, new windows shows tittle bar, the extension should be disabled and enabled again to hide all tittle bar.

**Comment by poehlerj** [comment]
Can you be more specific, under which circumstances, the title bar still shows? Is it a special type of application, or just sporadically. I am using the extension myself for about half a year and I didn't experience anything like that (using Firefox, Gnome-Applications, IntelliJ, and more).

**Comment by rcdeoliveira** [comment]
I did some tests and I realized the following: it only happens when I am using my laptop with an external environment, once I disable and enable again the extension it works normally. Happens only on windows that has title bars, like evolution, firefox, and emacs gtk. I am using Debian Bullseye (gnome-shell 3.34.3-1 with XServer).

**Comment by poehlerj** [comment]
I was finally able to reproduce this. For me this happens directly after login on XServer. Alt+F2+r then fixes the problem, but before that the bar doesn't get removed. 
I will implement a debugging system, in the next week or two, to have a deeper look into it. It seems kinda hard to debug, when bugs only happen sporadically...

**Comment by poehlerj** [comment]
I rewrote parts of the code and hope, that the extension is now working better. @rcdeoliveira Could you try this out again, as soon, as the extension is reviewed and available on extensions.gnome.org and give me feedback, if this is fixed now?

**Comment by rcdeoliveira** [comment]
@poehlerj I've testing this and it's working fine. Thank you so much (I did installation from github sources).
