### ISSUE TITLE
Gnome 40?

### ISSUE THREAD

**Issue by ewwhash** [poehlerj/no-title-bar#32]

**Comment by poehlerj** [comment]
Hey @BrightYC,
you can check out the changes done here: #31 (basically just a minor tweak, but the settings are not yet working)
I myself am currently unable to test this: I'm running Fedora 33, while Fedora 34 with Gnome 40 is not yet officially released and I don't really want to move my productive system onto that quite yet. Additionally I own an ARM Notebook with Manjaro ARM, where Gnome 40 hasn't hit the stable branch yet as well.
If you can confirm that the basic changes in that PR are working that would be great, but please understand that I really only want to release something I was able to test myself which is also why "new-gnome-version-updates" have always been lacking by a couple of weeks in the past.

I will keep this open until we have verified support for Gnome 40.

**Comment by ewwhash** [comment]
Sorry, i decided to switch to Sway XD

**Comment by poehlerj** [comment]
A Gnome 40 compatible version of the extension is now available from extensions.gnome.org. Closing this
