### ISSUE TITLE
"Show buttons for snapped windows" doesn't work as intended on Ubuntu 19.10

### ISSUE THREAD

**Issue by tognee** [poehlerj/no-title-bar#4]
Just did a clean install of Ubuntu 19.10 and installed the extension (from extensions.gnome.org and from source)
Having the "Show buttons for all windows" option disabled and "Show buttons for snapped windows" option enabled it should show the buttons in the top bar when the window is snapped.
But it's just like the option isn't enabled

![Schermata del 2020-02-06 16-36-16](https://user-images.githubusercontent.com/18465347/73952052-d45d5180-48fe-11ea-8080-8ec7866db798.png)

**Comment by poehlerj** [comment]
I merged the pull request, but am currently hunting a sporadically appearing bug, that the buttons show on a minimized GTK-Window like gnome-settings that shouldn't be altered by the extension at all. Did you experience anything like this?

**Comment by tognee** [comment]
Didn't experience that issue in my testings.
