### ISSUE TITLE
gtk-warning

### ISSUE THREAD

**Issue by IjonFryderyk** [poehlerj/no-title-bar#8]
Hi, great extension! 
Unfortunately I get this warning: 
gtk-warning ** theme parsing error gtk.css:3:0: expected valid sector

Apparently this is the "valid" line: 
[object GjsModule byteArray]

I get this warning when I open Sublime from Midnight Commander.  
I'm on Ubuntu 18.04 Gnome.

**Comment by poehlerj** [comment]
I currently don't know, if that is a problem with this extension. Do you have any more information on this?

**Comment by IjonFryderyk** [comment]
I'm now on Ubuntu 20.04 and everything works fine. Thanks! :)
