### ISSUE TITLE
Theme switching does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by jmico** [poehlerj/no-title-bar#9]
Theme setting is ignored, even after session restart.
The extension always uses Yaru style (the default for 20.04).
It looks good, so I guess this is a minor problem.

![Screenshot](https://user-images.githubusercontent.com/84746/80552122-07fac580-899c-11ea-8e96-a89d6fa7bcdf.png)

**Comment by poehlerj** [comment]
I have fixed it, but yet I have only tested it on Gnome 3.34. I will update probably today, fix another problem on Gnome 3.36 and then release this fix.

**Comment by poehlerj** [comment]
I have tested this with Gnome 3.36 and verified it fixed. I will close this issue, the extension is currently under review at extensions.gnome.org. This could take a while, since there are quite a lot of changes in there, but hopefully it is available next week.
